### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by ianbollinger** [lukerandall/haskellmode-vim#16]
Can someone get Claus Reinke to declare what license he released the original under?

**Comment by ches** [comment]
cc @clausreinke

**Comment by clausreinke** [comment]
Every time I think this has been replaced by more modern and maintained plugins, it comes back from the past to haunt me  (see [my answer on stackoverflow](http://stackoverflow.com/questions/20622390/is-haskellmode-vim-dead/20634599#20634599) !-). Surely there must be something better these days, if indeed it is still working at all.

There have been various distribution channels with whatever license the distributor needed - simple BSD or MIT should be fine. And if people really still find this useful, it would be even better if someone were to step forward and take over the project.

**Comment by ches** [comment]
There are indeed a slew of Haskell plugins for Vim around these days, but many of them aren't as comprehensive (which could be a good thing, some folks like to pick and choose features from plugins with a narrower scope, and maintaining larger ones is perhaps more daunting). So even if a lot of updates to `haskellmode-vim` are needed by now, it's nice to know that we can safely re-use code even if we just want to disassemble it for spare parts :wink:

Thanks for the prompt response @clausreinke!

**Comment by lukerandall** [comment]
Thanks @clausreinke. I will add a BSD license.
